name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        poetry install
    - name: Check formatting with Black
      run: |
        poetry run black --check .
    - name: Lint with pylint
      run: |
        poetry run pylint ftools
    - name: Test with pytest
      run: |
        poetry run pytest
