name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python: 3.8.0
        poetry_version: 0.12.17
        args: install
    - name: Check formatting with Black
      run: |
        poetry run black --check .
    - name: Lint with pylint
      run: |
        poetry run pylint ftools
    - name: Test with pytest
      run: |
        poetry run pytest
